version: "3.8"
services: 
  nginx: # 192.168.32.3/20
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYARGUMENTO: "Soy un argumento desde docker compose"
    container_name: nginx_svc
    restart: always
    environment: 
      MYVARIABLE: "este es un mensaje desde docker-compose"
    ports: 
      - 8080:80
    volumes:
      - ./html/:/usr/share/nginx/html
    networks:
      nginx_network:
        aliases:
          - nginx_host
  nginx2: # 192.168.32.2/20
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYARGUMENTO: "Soy un argumento desde docker compose"
    container_name: nginx2_svc
    restart: always
    environment: 
      MYVARIABLE: "este es un mensaje desde docker-compose"
    ports: 
      - 8180:80
    volumes:
      - ./html2/:/usr/share/nginx/html
    networks:
      nginx_network:
        aliases:
          - nginx2_host
volumes:
  html: {}
  html2: {}
networks:
  nginx_network:
    name: nginx_net
    driver: bridge
    ipam:
      driver: default